import type { ReportDescriptor } from "@modules/reports/core/types";
import { ROLE_IDS } from "@core/constants/roles";
import {
  getReportEquipmentsRows,
  type ReportEquipmentsFilters,
} from "../services/report-equipments.service";

export const equipmentsReport: ReportDescriptor<ReportEquipmentsFilters> = {
  name: "equipments",
  roles: [ROLE_IDS.ADMINISTRADOR],
  sheet: "Inventario Equipos",
  fileBase: "inventory_report",
  columns: [
    { key: "headquarters", label: "SEDE", width: 20 },
    { key: "name", label: "NOMBRE EQUIPO", width: 30 },
    { key: "typeEquipment", label: "TIPO EQUIPO", width: 20 },
    { key: "brand", label: "MARCA", width: 20 },
    { key: "model", label: "MODELO", width: 20 },
    { key: "serial", label: "SERIAL", width: 30 },
    { key: "systemOperating", label: "SISTEMA OPERATIVO", width: 30 },
    { key: "mac", label: "MAC", width: 30 },
    { key: "purchaseDate", label: "FECHA DE COMPRA", width: 30 },
    { key: "warrantyTime", label: "TIEMPO DE GARANTIA", width: 30 },
    { key: "warranty", label: "GARANTIA", width: 30 },
    { key: "deliveryDate", label: "FECHA DE ENTREGA", width: 30 },
    { key: "inventoryNumber", label: "NUMERO DE INVENTARIO", width: 30 },
    { key: "dateCreated", label: "FECHA DE CREACION", width: 30 },
    { key: "dateUpdate", label: "FECHA DE ACTUALIZACION", width: 30 },
    { key: "dhcp", label: "DHCP", width: 20 },
    { key: "ipAddress", label: "DIRECCION IP", width: 30 },
    { key: "userResponsable", label: "USUARIO RESPONSABLE", width: 30 },
    { key: "lock", label: "BLOQUEO", width: 20 },
    { key: "lockPassword", label: "CONTRASENA DE BLOQUEO", width: 30 },
    { key: "peripheralsName", label: "NOMBRE PERIFERICO", width: 30 },
    { key: "peripheralsBrand", label: "MARCA PERIFERICO", width: 30 },
    { key: "peripheralsModel", label: "MODELO PERIFERICO", width: 30 },
    { key: "peripheralsSerial", label: "SERIAL PERIFERICO", width: 30 },
    { key: "peripheralsOtherData", label: "OTROS DATOS PERIFERICO", width: 30 },
    { key: "peripheralsStatus", label: "ESTADO PERIFERICO", width: 30 },
    { key: "peripheralsInventoryNumber", label: "NUMERO INVENTARIO PERIFERICO", width: 30 },
    { key: "peripheralsDateCreated", label: "FECHA DE REGISTRO PERIFERICO", width: 30 },
    { key: "peripheralsDateUpdate", label: "FECHA DE ULTIMA ACTUALIZACION PERIFERICO", width: 30 },
    { key: "softwareName", label: "NOMBRE SOFTWARE", width: 30 },
    { key: "softwareVersion", label: "VERSION SOFTWARE", width: 30 },
    { key: "softwareLicense", label: "LICENCIA SOFTWARE", width: 30 },
    { key: "softwareOtherData", label: "OTROS DATOS SOFTWARE", width: 30 },
    { key: "softwareInstallationDate", label: "FECHA DE INSTALACION SOFTWARE", width: 30 },
    { key: "softwareStatus", label: "ESTADO SOFTWARE", width: 30 },
    { key: "softwareDateCreated", label: "FECHA DE REGISTRO SOFTWARE", width: 30 },
    { key: "softwareDateUpdated", label: "FECHA DE ULTIMA ACTUALIZACION SOFTWARE", width: 30 },
    { key: "componentName", label: "NOMBRE COMPONENTE", width: 30 },
    { key: "componentBrand", label: "MARCA COMPONENTE", width: 30 },
    { key: "componentCapacity", label: "CAPACIDAD COMPONENTE", width: 30 },
    { key: "componentSpeed", label: "VELOCIDAD COMPONENTE", width: 30 },
    { key: "componentOtherData", label: "OTROS DATOS COMPONENTE", width: 30 },
    { key: "componentModel", label: "MODELO COMPONENTE", width: 30 },
    { key: "componentDateCreated", label: "FECHA DE REGISTRO COMPONENTE", width: 30 },
    { key: "componentDateUpdated", label: "FECHA DE ULTIMA ACTUALIZACION COMPONENTE", width: 30 },
  ],
  header: {
    kind: "grouped",
    groupRows: 2,
    style: "primary",
    groups: [
      { label: "DATOS DEL EQUIPO", from: "headquarters", to: "lockPassword" },
      { label: "DATOS DE PERIFÉRICOS", from: "peripheralsName", to: "peripheralsDateUpdate" },
      { label: "DATOS DE SOFTWARE", from: "softwareName", to: "softwareDateUpdated" },
      { label: "DATOS DE COMPONENTES", from: "componentName", to: "componentDateUpdated" },
    ],
  },
  fetchRows: getReportEquipmentsRows,
  onEmpty: "throw-404",
  notFoundMessage: "Inventory Equipments Not Found.",
  previewNotFoundMessage: "Data Equipments Not Found.",
  swagger: {
    summary: "Descarga reporte de inventario de equipos en Excel",
    previewSummary: "Vista previa JSON del reporte de inventario de equipos",
    filters: {
      dateStart: { type: "string", format: "date", description: "Fecha de inicio del filtro" },
      dateEnd: { type: "string", format: "date", description: "Fecha de fin del filtro" },
    },
  },
};
