import type { ReportDescriptor } from "@modules/reports/core/types";
import { ROLE_GROUPS } from "@core/constants/roles";
import {
  getReportDemandInducedRows,
  type ReportDemandInducedFilters,
} from "../services/report-demand-induced.service";

export const demandInducedReport: ReportDescriptor<ReportDemandInducedFilters> = {
  name: "demand-induced",
  roles: ROLE_GROUPS.ADMIN_NURSING,
  sheet: "Reporte Demandas Inducidas",
  fileBase: "Reporte_Demandas_Inducidas",
  columns: [
    { key: "tipo_documento", label: "TIPO DOC", width: 20 },
    { key: "numero_identificacion", label: "NUMERO DOC", width: 20 },
    { key: "fecha_actividad", label: "Fecha actividad DI", width: 20 },
    { key: "elemento_demanda", label: "Elemento DI", width: 30 },
    { key: "tipo_elemento", label: "Tipo elemento", width: 30 },
    { key: "objetivo", label: "Objetivo", width: 30 },
    { key: "numero_telefono_contacto", label: "Número de telefono con el que se establece el contacto", width: 20 },
    { key: "clasificacion_seguimiento", label: "Clasificación del seguimiento", width: 30 },
    { key: "persona_recibe_llamada", label: "Persona que recibe la llamada", width: 30 },
    { key: "relacion_usuario", label: "Relación con el usuario", width: 30 },
    { key: "fecha_llamada", label: "Fecha de llamada", width: 20 },
    { key: "hora_llamada", label: "hora de llamada", width: 20 },
    { key: "texto_llamada", label: "Texto de la llamada", width: 30 },
    { key: "barreras_acceso", label: "Presenta barreras o dificultades para el acceso al tratamiento?", width: 30 },
    { key: "area_dificultad", label: "Area con la que presenta la dificultad?", width: 30 },
    { key: "area_eps", label: "Area de la EPS", width: 30 },
    { key: "resumen_actividades", label: "Resumen de las actividades realizadas durante el seguimiento", width: 30 },
    { key: "condicion_final_usuario", label: "Condición final usuario", width: 30 },
    { key: "soportes_recuperados", label: "Soportes recuperados", width: 30 },
    { key: "departamento", label: "Departamento", width: 20 },
    { key: "municipio", label: "Municipio", width: 20 },
    { key: "barrio_vereda", label: "Barrio o vereda", width: 20 },
    { key: "numero_telefono", label: "Número telefono", width: 20 },
    { key: "correo_electronico", label: "Correo electronico", width: 30 },
    { key: "resultado_llamada", label: "Resultado de llamada", width: 30 },
    { key: "fecha_envio", label: "Fecha de envío", width: 30 },
    { key: "hora_envio", label: "Hora de envío", width: 30 },
    { key: "texto_mensaje", label: "Texto del mensaje", width: 30 },
    { key: "fecha_visita", label: "Fecha de visita", width: 30 },
    { key: "resumen_visita", label: "Resumen de visita", width: 30 },
    { key: "motivo_visita_no_efectiva", label: "Motivo de visita no efectiva", width: 30 },
    { key: "persona_seguimiento", label: "Persona que realiza el seguimiento", width: 30 },
    { key: "area_persona", label: "Área", width: 30 },
    { key: "programa", label: "Programa", width: 30 },
    { key: "fecha_asignacion_cita", label: "Fecha de asignacion de cita", width: 30 },
    { key: "profesional", label: "Profesional", width: 30 },
    { key: "headquarter", label: "Sede", width: 30 },
  ],
  header: {
    kind: "grouped",
    groupRows: 2,
    style: "primary",
    labelStyle: "neutral",
    groups: [
      { label: "DEMANDA INDUCIDA", from: "tipo_documento", to: "objetivo" },
      { label: "LLAMADA TELEFÓNICA EFECTIVA", from: "numero_telefono_contacto", to: "soportes_recuperados", color: "FF46B1C9" },
      { label: "ACTUALIZACIÓN DE DATOS DE UBICACIÓN", from: "departamento", to: "correo_electronico" },
      { label: "LLAMADA NO EFECTIVA", from: "resultado_llamada", to: "resultado_llamada", color: "FF46B1C9" },
      { label: "MENSAJE DE TEXTO", from: "fecha_envio", to: "texto_mensaje" },
      { label: "VISITA PREVENTIVA DE SALUD", from: "fecha_visita", to: "resumen_visita", color: "FF46B1C9" },
      { label: "PERSONA QUE REALIZA EL SEGUIMIENTO", from: "motivo_visita_no_efectiva", to: "headquarter" },
    ],
  },
  fetchRows: getReportDemandInducedRows,
  parseFilters: (body, req) => ({
    dateStart: body.dateStart as string | undefined,
    dateEnd: body.dateEnd as string | undefined,
    headquarter: body.headquarter as string | undefined,
    convenio: body.convenio as string | undefined,
    rolUser: req.user?.rol,
    userId: req.user?.id,
  }),
  onEmpty: "throw-404",
  notFoundMessage: "Demanda inducida no encontrada.",
  previewNotFoundMessage: "Data Demand Induced Not Found.",
  swagger: {
    summary: "Descarga reporte de demanda inducida en Excel",
    previewSummary: "Vista previa JSON del reporte de demanda inducida",
    filters: {
      dateStart: { type: "string", format: "date", description: "Fecha de inicio del filtro" },
      dateEnd: { type: "string", format: "date", description: "Fecha de fin del filtro" },
      headquarter: { type: "string", description: "Sede para filtrar los resultados" },
      convenio: { type: "string", description: "Convenio para filtrar los resultados" },
    },
  },
};
