import { Router } from "express";

import radicacionRoutes from './radicacion.routes';
import tipoDocumentoRoutes from './tipo-documento_routes';
import convenioRoutes from './convenio_routes';
import ipsPrimariaRoutes from './ips-primaria_routes';
import especialidadRoutes from './especialidad_routes';
import ipsRemiteRoutes from './ips-remite_routes';
import lugarRadicacionRoutes from './lugar-radicacion.routes';
import grupoServiciosRoutes from './grupo-servicios_routes';
import estadosRoutes from './estados_routes';
import cupsRadicadosRoutes from './cups-radicados_routes';
import diagnosticosRoutes from './diagnosticos-routes';
import estadoSeguimientoRoutes from './estados-seguimientos_routes';
import municipioRoutes from './municipio_routes';
import pacientesRoutes from './pacientes_routes';
import rolesRoutes from './roles_routes';
import seguimientoAuxiliarRoutes from './seguimiento-auxiliar_routes';
import serviciosRoutes from './servicio_routes';
import servicioSolicitadoRoutes from './servicio-solicitado_routes';
import unidadFuncionalRoutes from './unidad-funcional_routes';
import usuariosRoutes from './usuarios.routes';
import soportesRoutes from './soportes_routes';
import authRoutes from './auth_routes';
import carpetasRoutes from './carpetas_routes';
import archivosRoutes from './archivos_routes';
import cirugiasRoutes from './cirugias_routes';
import seguimientoAuxiliarCirugiasRoutes from './seguimiento-auxiliar-cirugia_routes';
import reportExcelRoutes from './report-excel_routes';
import certificateRoutes from './certificados_routes';
import accesoriosRoutes from './accesorios-equipos.routes';
import equiposRoutes from './equipos.routes';
import dispositivoRedRoutes from './dispositivos-red_routes';
import seguimientoEquipos from './seguimiento-equipos-routes';
import departamentoRoutes from './departamentos_routes';
import seguimientoDispositivosRed from './seguimiento-dispositivos-red_routes';
import componenteRoutes from './componentes_routes';
import softwareRoutes from './software_routes';
import activeBrakesRoutes from './pausas-activas.routes';
import eventosRoutes from './eventos_routes';
import serviciosEjecutadosRoutes from './servicios-ejecutados_routes';
import serviciosGeneralesRoutes from './servicios-generales_routes';
import notaTencicaRoutes from './notas-tecnicas_routes';
import cartaRecobroRoutes from './carta-recobro_routes';
import pacientesCoosalud from './pacientes-coosalud_routes'
import enviarEmail from './send-emails_routes';
import cvPublicRoutes from './cv-public_routes';
import ticketsRoutes from './tickets.routes';
import statusTicketsRoutes from './estados-tickets_routes';
import prioridadRoutes from './prioridad.routes';
import categoriasRoutes from './categorias.routes';
import comentariosRoutes from './comentarios_routes';
import encuestasSatisfaccionRoutes from './encuestas-satisfaccion_routes';
import notificacionesRoutes from './notificaciones.routes';
import pushSubscription from './push-subscription_routes';
import registerEntries from './registro-entrada_routes';
import inventarioGeneralRoutes from './inventario-general.routes';
import clasificacionRoutes from './clasificacion_routes';
import activosRoutes from './activos_routes';
import materiaLRoutes from './material_routes';
import estadoIvGeneral from './estado-iv-general_routes';
import tipoAreaRoutes from './tipo-area_routes';
import tipoActivoRoutes from './tipo-activo_routes';
import areaDependenciaRoutes from './area-dependencia_routes';
import seguimientoGeneralRoutes from './seguimiento-inventario-general_routes';
import participantesRoutes from './participantes_routes';
import celularesRoutes from './celular.routes';
import televisoresRoutes from './televisor_routes';
import seguimientoTelevisorRoutes from './seguimiento-televisor_routes';
import seguimientoCelularesRoutes from './seguimiento-celulares_routes';
import elementDemandaInducidaRoutes from './elemento-demanda-inducida.route';
import typeElementDemandInducedRoutes from './tipo-demanda-inducida.route';
import objetiveDemandInducedRoutes from './objetivo-demanda-inducida.route';
import relationUserRoutes from './relacion-usuario.route';
import areaEpsRoutes from './area-eps.route';
import summaryActivityRoutes from './resumen-seguimiento-actividad.route';
import resultCallsRoutes from './resultado-llamada.route';
import areaPersonRoutes from './area-persona-seguimiento.route';
import reasonVisitRoutes from './motivo-visita.route';
import professionalRoutes from './profesionales.route';
import programsRoutes from './programa.route';
import demandInducedRoutes from './demanda-inducida.routes';
import goalsRoutes from './programa-meta-historico.routes';
import areaRoutes from './area.routes';
import cargoRoutes from './cargo.routes';
import permisosRoutes from './permission-request.routes';

const router = Router();

// * Rutas
router.use( radicacionRoutes);
router.use( tipoDocumentoRoutes);
router.use( convenioRoutes);
router.use( ipsPrimariaRoutes);
router.use( especialidadRoutes);
router.use( lugarRadicacionRoutes);
router.use( ipsRemiteRoutes);
router.use( grupoServiciosRoutes);
router.use( estadosRoutes);
router.use( cupsRadicadosRoutes);
router.use( diagnosticosRoutes);
router.use( estadoSeguimientoRoutes);
router.use( municipioRoutes);
router.use( pacientesRoutes);
router.use( rolesRoutes);
router.use( seguimientoAuxiliarRoutes);
router.use( serviciosRoutes);
router.use( servicioSolicitadoRoutes);
router.use( unidadFuncionalRoutes);
router.use( usuariosRoutes);
router.use( soportesRoutes);
router.use( authRoutes);
router.use(carpetasRoutes);
router.use(archivosRoutes);
router.use(cirugiasRoutes);
router.use(seguimientoAuxiliarCirugiasRoutes);
router.use(reportExcelRoutes);
router.use(certificateRoutes);
router.use(accesoriosRoutes);
router.use(equiposRoutes);
router.use(dispositivoRedRoutes);
router.use(seguimientoEquipos);
router.use(departamentoRoutes);
router.use(seguimientoDispositivosRed);
router.use(componenteRoutes);
router.use(softwareRoutes);
router.use(activeBrakesRoutes);
router.use(eventosRoutes);
router.use(serviciosEjecutadosRoutes);
router.use(serviciosGeneralesRoutes);
router.use(notaTencicaRoutes);
router.use(cartaRecobroRoutes); 
router.use(pacientesCoosalud);
router.use(enviarEmail);
router.use(cvPublicRoutes); // Rutas públicas para CVs - NO requieren autenticación
router.use(ticketsRoutes);
router.use(statusTicketsRoutes);
router.use(prioridadRoutes);
router.use(categoriasRoutes);
router.use(comentariosRoutes);
router.use(encuestasSatisfaccionRoutes);
router.use(notificacionesRoutes);
router.use(pushSubscription);
router.use(registerEntries);
router.use(inventarioGeneralRoutes);
router.use(clasificacionRoutes);
router.use(activosRoutes);
router.use(materiaLRoutes);
router.use(estadoIvGeneral);
router.use(tipoAreaRoutes);
router.use(tipoActivoRoutes);
router.use(areaDependenciaRoutes);
router.use(seguimientoGeneralRoutes);
router.use(participantesRoutes);
router.use(celularesRoutes);
router.use(televisoresRoutes);
router.use(seguimientoTelevisorRoutes);
router.use(seguimientoCelularesRoutes);
router.use(elementDemandaInducidaRoutes);
router.use(typeElementDemandInducedRoutes);
router.use(objetiveDemandInducedRoutes);
router.use(relationUserRoutes);
router.use(areaEpsRoutes);
router.use(summaryActivityRoutes);
router.use(resultCallsRoutes);
router.use(areaPersonRoutes);
router.use(reasonVisitRoutes);
router.use(professionalRoutes);
router.use(programsRoutes);
router.use(demandInducedRoutes);
router.use(goalsRoutes);
router.use(areaRoutes);
router.use(cargoRoutes);
router.use(permisosRoutes);

export default router;