import { MigrationInterface, QueryRunner, Table } from "typeorm";

export class CreateTablePrograma1751381414826 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.createTable(
            new Table({
                name: "programa",
                columns: [
                    {
                        name: "id",
                        type: "int",
                        isPrimary: true,
                        isGenerated: true,
                        generationStrategy: "increment",
                    },
                    {
                        name: "nombre",
                        type: "varchar",
                        isNullable: false,
                    },
                    {
                        name: "created_at",
                        type: "timestamp",
                        default: "CURRENT_TIMESTAMP",
                    },
                    {
                        name: "updated_at",
                        type: "timestamp",
                        default: "CURRENT_TIMESTAMP",
                        onUpdate: "CURRENT_TIMESTAMP",
                    },
                ],
            }),
            true
        );

        await queryRunner.query(`
            INSERT INTO programa (nombre)
            VALUES
            ('Acceso a servicios de Salud'),
            ('DT cáncer mama'),
            ('VIH'),
            ('Zika'),
            ('Grupos de riesgo PAIS'),
            ('Ruta Materno perinatal'),
            ('Trastornos mentales y del comportamiento'),
            ('Alteraciones y trastornos de la salud bucal'),
            ('Cáncer'),
            ('DT cancer próstata'),
            ('Condición materno  perinatal'),
            ('Enfermedades Infecciosas'),
            ('Enfermedades Zoonoticas'),
            ('Accidentes y  Enfermedad laborales'),
            ('Enfermedades huerfanas'),
            ('Alteraciones y trastornos visuales'),
            ('Alteraciones y trastornos de la audición y comunicación'),
            ('trastornos degenerativos neuropatías y autoinmunes'),
            ('Trastornos asociados al uso de SPA'),
            ('Alteraciones nutricionales'),
            ('Infancia'),
            ('Violencias'),
            ('IRA'),
            ('Salud Oral'),
            ('Viruela simica'),
            ('Juventud'),
            ('Lineamientos generales Programas PYP NEPS'),
            ('Politica de atención integral de Salud'),
            ('Metodologia de evaluación NEPS'),
            ('Modelo de gestión extramural'),
            ('Otras normas'),
            ('Planificación familiar'),
            ('Primera Infancia'),
            ('Programa demanda Inducida'),
            ('Resolución 3280 2020'),
            ('Resolución 4505 de 2012'),
            ('Ruta PYMS'),
            ('Sistema de información'),
            ('Vacunación'),
            ('Vejez'),
            ('Estrategia 4X4'),
            ('Adolescencia'),
            ('Agendamiento'),
            ('Programa de educación en Salud'),
            ('Seguimiento al cumplimiento de indicadores PYMS'),
            ('Otro'),
            ('Accidente ofidico'),
            ('Bajo peso al nacer'),
            ('Cancer de mama y cuello uterino'),
            ('cancer en menores de 18 años'),
            ('Chagas'),
            ('Chikunguña'),
            ('Adultez'),
            ('Colera'),
            ('Consumo sustancias psicoactivas'),
            ('COVID 19'),
            ('Datos básicos y otros eventos'),
            ('Defectos congenitos'),
            ('Dengue'),
            ('Desnutrición en menores de 5 años'),
            ('Difteria'),
            ('Ebola'),
            ('Encefalitis Equina'),
            ('Agendamiento'),
            ('Enfermedad de Creutzfeldt Jakob'),
            ('Enfermedad transmitida por alimentos'),
            ('Enfermedades Huerfanas o raras'),
            ('ETV'),
            ('Evento supuestamente atribuido a la vacunación'),
            ('Exposición a flúor'),
            ('Fiebre amarilla'),
            ('Fiebre tifoidea y paratifoidea'),
            ('Hepatitis A'),
            ('Hepatitis B y C'),
            ('Caracterización poblacional'),
            ('Indicadores Salud Pública'),
            ('Infección respiratoria aguda'),
            ('Intento de suicidio'),
            ('Intoxicaciones'),
            ('Leishmaniasis'),
            ('Lepra'),
            ('Leptospirosis'),
            ('lesiones por artefactos explosivos'),
            ('Lineamientos INS'),
            ('Linemientos generales'),
            ('Descuentos a la facturación'),
            ('Malaria'),
            ('Meningitis'),
            ('Morbilidad materna extrema'),
            ('Mortalidad en menores de 5 años'),
            ('Mortalidad materna'),
            ('Mortalidad perinatal y neonatal'),
            ('Oncocercosis'),
            ('Paralisis flacida Aguda'),
            ('Parotiditis'),
            ('DT cancer colorectal'),
            ('Proceso de notificación EISP'),
            ('Rabia'),
            ('Resolución 459'),
            ('Salud Mental'),
            ('Sarampión'),
            ('Sarampión y Rubeola'),
            ('Sifilis'),
            ('Sindrome de Rubeola Congenita'),
            ('Sistema de alertas tempranas'),
            ('Otro'),
            ('Sistema de vigilancia en SP'),
            ('Tetanos accidental'),
            ('Tetanos neonatal'),
            ('Tosferina'),
            ('Tracoma'),
            ('Tuberculosis'),
            ('Unidades analisis'),
            ('Varicela'),
            ('Consulta de Atención Integral RPYMS'),
            ('DT por ADN VPH'),
            ('DT por   Citología'),
            ('Tamizaje de Hemoglobina'),
            ('Tamizaje de Riesgo cardiovascular'),
            ('Tamizaje de Riesgo ITS'),
            ('Consulta Preconcepcional'),
            ('Consulta de Lactancia Materna'),
            ('Talleres Educación Grupal'),
            ('Consulta Médico Personal'),
            ('Otro Eventos de Interés en Salud Pública'),
            ('Población Diferencial Victimas Conflicto Armado'),
            ('Población Diferencia Ruralidad'),
            ('Población Diferencial Etnia'),
            ('Otra Población Diferencial'),
            ('Posthospitalizado'),
            ('Sentencias Corte Interamerica de Derechos'),
            ('Infancia por enfermería'),
            ('Urología RPMS'),
            ('Ginecología RPMS'),
            ('Medicina familiar RPMS'),
            ('Medicina general RPMS'),
            ('Vacunación VPH'), 
            ('Vacunación triple viral'),
            ('Vacunación menores de 6'),
            ('Vacuna bivalente comorbilidades'),
            ('Vacuna bivalente mayores de 60'),
            ('Hipertension Arterial (HTA)'),
            ('Diabetes Mellitus (DM)'),
            ('Odontologia'),
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.dropTable("programa");
    }
}