import type { ReportDescriptor } from "@modules/reports/core/types";
import { ROLE_GROUPS } from "@core/constants/roles";
import {
  getReportRadicacionRows,
  type ReportRadicacionFilters,
} from "../services/report-radicacion.service";

export const radicacionReport: ReportDescriptor<ReportRadicacionFilters> = {
  name: "radicacion",
  roles: ROLE_GROUPS.REPORT_MANAGERS,
  sheet: "Reporte CUPS",
  fileBase: "Reporte_CUPS",
  columns: [
    { key: "radicadoDate", label: "Fecha-hora", width: 20 },
    { key: "Id", label: "Numero Radicado", width: 10 },
    { key: "Tipo_de_documento", label: "Tipo Documento", width: 20 },
    { key: "Nombre_del_paciente", label: "Nombre Paciente", width: 30 },
    { key: "Numero_documento", label: "Número Documento", width: 30 },
    { key: "Telefono_celular", label: "Número Celular", width: 20 },
    { key: "Telefono_fijo", label: "Telefono Fijo", width: 20 },
    { key: "Correo_electronico", label: "Email", width: 30 },
    { key: "Direccion", label: "Direccion", width: 30 },
    { key: "Convenio", label: "Convenio", width: 20 },
    { key: "IPS_Primaria", label: "IPS Primaria", width: 20 },
    { key: "Fecha_de_orden", label: "Fecha Orden", width: 20 },
    { key: "Lugar_de_radicacion", label: "Lugar Radicación", width: 30 },
    { key: "IPS_Remitente", label: "IPS Remite", width: 30 },
    { key: "Profesional", label: "Profesional", width: 30 },
    { key: "Especialidad", label: "Especialidad", width: 30 },
    { key: "codigo_diagnostico", label: "Cod Diagnostico", width: 20 },
    { key: "descripcion_diagnostico", label: "Descripcion Diagnostico", width: 30 },
    { key: "Grupo_de_servicios", label: "Grupo Servicio", width: 20 },
    { key: "Servicios", label: "Tipo Servicio", width: 20 },
    { key: "Radicador", label: "Auxiliar Radicador", width: 20 },
    { key: "Auditora", label: "Nombre Auditora", width: 20 },
    { key: "Fecha_de_auditoria", label: "Fecha Auditoria", width: 20 },
    { key: "Codigo_cups", label: "Codigo CUPS", width: 30 },
    { key: "Descripcion_cups", label: "Descripcion CUPS", width: 30 },
    { key: "Estado_cups", label: "Estado CUPS", width: 20 },
    { key: "Observacion_cups", label: "Observacion CUPS", width: 20 },
    { key: "Unidad_funcional", label: "Unidad Funcional", width: 30 },
    { key: "Fecha_actualizacion", label: "Ultima Modificacion", width: 20 },
    { key: "Observacion_seguimiento_auxiliar", label: "Seguimiento Auxiliar", width: 30 },
  ],
  header: { kind: "simple", style: "plain" },
  fetchRows: getReportRadicacionRows,
  onEmpty: "none",
  previewNotFoundMessage: "Data Radicacion not found.",
  swagger: {
    summary: "Descarga reporte de radicaciones filtrado en Excel",
    previewSummary: "Vista previa JSON del reporte de radicaciones (mismos filtros que el Excel)",
    filters: {
      statusCups: { type: "string", description: "Filtro por estado del CUPS" },
      dateStart: { type: "string", format: "date", description: "Fecha de inicio del filtro" },
      dateEnd: { type: "string", format: "date", description: "Fecha de fin del filtro" },
      cupsCode: { type: "string", description: "Filtro por código CUPS" },
      specialty: { type: "string", description: "Filtro por especialidad" },
    },
  },
};
