import type { ReportDescriptor } from "@modules/reports/core/types";
import { ROLE_IDS } from "@core/constants/roles";
import {
  getReportPqrsdfRows,
  type ReportPqrsdfFilters,
} from "../services/report-pqrsdf.service";

export const pqrsdfReport: ReportDescriptor<ReportPqrsdfFilters> = {
  name: "pqrsdf",
  roles: [ROLE_IDS.ADMINISTRADOR, ROLE_IDS.SIAU, ROLE_IDS.CALIDAD],
  sheet: "Reporte PQRSDF",
  fileBase: "Reporte_PQRSDF",
  columns: [
    { key: "Nombre_del_paciente", label: "NOMBRE DE PACIENTE", width: 32 },
    { key: "Documento", label: "DOCUMENTO", width: 20 },
    { key: "Asegurador_EPS", label: "ASEGURADOR/EPS", width: 20 },
    { key: "Ente", label: "ENTE", width: 20 },
    { key: "Regimen", label: "REGIMEN", width: 20 },
    { key: "Novedad_presentada_por", label: "NOVEDAD PRESENTADA POR", width: 24 },
    { key: "Notifica_EPS", label: "NOTIFICA DE EPS", width: 20 },
    { key: "PQRS", label: "PQRS", width: 16 },
    { key: "Medio", label: "MEDIO", width: 18 },
    { key: "Numero_de_radicado", label: "NUMERO DE RADICADO", width: 20 },
    { key: "Fecha_de_radicacion", label: "FECHA DE RADICACION", width: 20 },
    { key: "Fecha_de_hallazgo", label: "FECHA DE HALLAZGO", width: 20 },
    { key: "Fecha_de_respuesta", label: "FECHA DE RESPUESTA", width: 20 },
    { key: "Oportunidad_desde_radicacion", label: "OPORTUNIDAD DESDE RADICACION", width: 24 },
    { key: "Oportunidad_desde_hallazgo", label: "OPORTUNIDAD DESDE HALLAZGO", width: 24 },
    { key: "Via_utilizada_para_la_respuesta", label: "VIA UTILIZADA PARA LA RESPUESTA", width: 28 },
    { key: "Servicio", label: "SERVICIO", width: 24 },
    { key: "Respuesta", label: "RESPUESTA", width: 50 },
    { key: "Area_con_la_cual_se_resolvio_el_evento", label: "AREA CON LA CUAL SE RESOLVIO EL EVENTO", width: 30 },
    { key: "Clasificacion_final", label: "CLASIFICACION FINAL", width: 20 },
    { key: "Accion_de_mejora", label: "ACCION DE MEJORA", width: 18 },
    { key: "Plan_de_mejoramiento", label: "PLAN DE MEJORAMIENTO: ACCIONES TOMADAS/CORRECTIVOS", width: 50 },
    { key: "Fecha_del_seguimiento", label: "FECHA DEL SEGUIMIENTO", width: 22 },
    { key: "Seguimiento", label: "SEGUIMIENTO", width: 30 },
    { key: "Estado", label: "ESTADO", width: 16 },
    { key: "Indicador", label: "INDICADOR", width: 16 },
  ],
  header: { kind: "simple", style: "primaryDark", fontSize: 10, rowHeight: 30 },
  fetchRows: getReportPqrsdfRows,
  onEmpty: "throw-404",
  notFoundMessage: "No se encontraron PQRSDF en el rango especificado",
  previewNotFoundMessage: "Data PQRSDF Not Found.",
  swagger: {
    summary: "Descarga reporte de PQRSDF en Excel",
    previewSummary: "Vista previa JSON del reporte de PQRSDF (mismos filtros que el Excel)",
    filters: {
      startDate: { type: "string", format: "date", description: "Fecha de inicio del filtro (fecha de radicación)" },
      endDate: { type: "string", format: "date", description: "Fecha de fin del filtro (fecha de radicación)" },
      status: { type: "string", description: "Filtro por estado (ABIERTO, EN_GESTION, CERRADO)" },
      classification: { type: "string", description: "Filtro por clasificación" },
      instance: { type: "string", description: "Filtro por instancia" },
      patientDocument: { type: "string", description: "Filtro por documento del paciente" },
      originAreaId: { type: "integer", description: "Filtro por ID de área de origen" },
    },
  },
};
